# Generated by Django 2.1 on 2018-08-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('car_bodytype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_location', models.CharField(default='Brisbane', max_length=200)),
                ('order_date', models.DateTimeField(verbose_name='date published')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarRentalCompany.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_location', models.CharField(max_length=200)),
                ('store_phone_number', models.IntegerField()),
            ],
        ),
    ]
