# Generated by Django 2.1 on 2018-09-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalCompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_location',
            field=models.CharField(default='Brisbane', max_length=128),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_location',
            field=models.CharField(max_length=128),
        ),
    ]
