# Generated by Django 2.1 on 2018-09-13 08:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalCompany', '0002_auto_20180912_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='car',
            new_name='car_id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_location',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_location',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='car_drive',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_engine_size',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_fuel_system',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_makename',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_power',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_price_new',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='car',
            name='car_seating_capacity',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='car',
            name='car_series',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_series_year',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_standard_transmission',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_tank_capacity',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='car_wheelbase',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CarRentalCompany.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='order create date'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_pickup_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='order pickup date'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_pickup_store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_store_order_set', to='CarRentalCompany.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_return_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='order return date'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_return_store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='return_store_order_set', to='CarRentalCompany.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='store',
            name='store_city',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='store',
            name='store_phone',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='store',
            name='store_state',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(default='null', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='user_birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='user birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(default='null', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='null', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='user_occupation',
            field=models.CharField(default='null', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_bodytype',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=-1, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
