# Generated by Django 2.1 on 2018-09-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalCompany', '0004_auto_20180914_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
