# Generated by Django 2.1 on 2018-09-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalCompany', '0005_auto_20180914_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_phone',
            field=models.BigIntegerField(default=-1),
        ),
    ]
