# Generated by Django 2.1 on 2018-09-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalCompany', '0008_auto_20180915_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_latitude',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='store',
            name='store_longitude',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
