# Generated by Django 2.1 on 2018-10-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalCompany', '0011_order_order_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
